# YOU MAY MODIFY/EDIT THIS MODULE
# PUT ALL YOUR CONSTANTS HERE(VARIABLES THAT DO NOT CHANGE)


WIDTH = 800
HEIGHT = 600
BACKGROUND_COLOR = color(255) # or RGB: color(255, 0, 255)

PLAYER_SCALE = 0.5
TANK_SCALE = 0.5

PLAYER_SPEED = 5
