#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Long Nguyen

# Short bio or description (displayed in the header)
description: Resources including course materials for Computer Science and Mathematics. 
Resource for AP Computer Science A and AP Computer Science Principles. Introduction to 
Neural Network. Programming Animation. 


#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  github: longbaonguyen
  youtube: UCERxBOrkAgt1ofkgfh0dwkA

plugins:
  - jekyll-sitemap

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-126746295-1


# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://longbaonguyen.github.io/


#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
